//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string token {
            get {
                return ((string)(this["token"]));
            }
            set {
                this["token"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string roles {
            get {
                return ((string)(this["roles"]));
            }
            set {
                this["roles"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8000/api/v1/")]
        public string apiEndPoint {
            get {
                return ((string)(this["apiEndPoint"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SK")]
        public string stock {
            get {
                return ((string)(this["stock"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KD")]
        public string sale {
            get {
                return ((string)(this["sale"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("auth/")]
        public string authorizePath {
            get {
                return ((string)(this["authorizePath"]));
            }
            set {
                this["authorizePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("quotationitems")]
        public string quotationItemsPath {
            get {
                return ((string)(this["quotationItemsPath"]));
            }
            set {
                this["quotationItemsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("inventorys")]
        public string inventorysPath {
            get {
                return ((string)(this["inventorysPath"]));
            }
            set {
                this["inventorysPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("stockinplandetails")]
        public string stockinPlanDetailsPath {
            get {
                return ((string)(this["stockinPlanDetailsPath"]));
            }
            set {
                this["stockinPlanDetailsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("stockoutplandetails")]
        public string stockoutPlanDetailsPath {
            get {
                return ((string)(this["stockoutPlanDetailsPath"]));
            }
            set {
                this["stockoutPlanDetailsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("poitems")]
        public string poItemsPath {
            get {
                return ((string)(this["poItemsPath"]));
            }
            set {
                this["poItemsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("stockinreceiptdetails")]
        public string stockinReceiptDetailsPath {
            get {
                return ((string)(this["stockinReceiptDetailsPath"]));
            }
            set {
                this["stockinReceiptDetailsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("stockoutreceiptdetails")]
        public string stockoutReceiptDetailsPath {
            get {
                return ((string)(this["stockoutReceiptDetailsPath"]));
            }
            set {
                this["stockoutReceiptDetailsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("stockinplans")]
        public string stockinPlansPath {
            get {
                return ((string)(this["stockinPlansPath"]));
            }
            set {
                this["stockinPlansPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("stockoutplans")]
        public string stockoutPlansPath {
            get {
                return ((string)(this["stockoutPlansPath"]));
            }
            set {
                this["stockoutPlansPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("stockinreceipts")]
        public string stockinReceiptsPath {
            get {
                return ((string)(this["stockinReceiptsPath"]));
            }
            set {
                this["stockinReceiptsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("stockoutreceipts")]
        public string stockoutReceiptsPath {
            get {
                return ((string)(this["stockoutReceiptsPath"]));
            }
            set {
                this["stockoutReceiptsPath"] = value;
            }
        }
    }
}
